### ISSUE TITLE
SwipeBackLayout Error

### ISSUE THREAD

**Issue by sdroider** [rom4ek/ArcNavigationView#11]
Crash app example:
`01-27 15:29:27.982 10977-10977/com.appdroid.develop.fantasyslide E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.appdroid.develop.fantasyslide, PID: 10977
                                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.appdroid.develop.fantasyslide/com.appdroid.develop.fantasyslide.UniversalActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class me.imid.swipebacklayout.lib.SwipeBackLayout
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
                                                                                       at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5523)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                                    Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class me.imid.swipebacklayout.lib.SwipeBackLayout
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                       at me.imid.swipebacklayout.lib.app.SwipeBackActivityHelper.onActivityCreate(SwipeBackActivityHelper.java:28)
                                                                                       at com.appdroid.develop.fantasyslide.UniversalActivity.onCreate(UniversalActivity.java:28)
                                                                                       at android.app.Activity.performCreate(Activity.java:6303)
                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                                       at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5523) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                                                    Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class me.imid.swipebacklayout.lib.SwipeBackLayout
                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:649)
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768)
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:496)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                       at me.imid.swipebacklayout.lib.app.SwipeBackActivityHelper.onActivityCreate(SwipeBackActivityHelper.java:28) 
                                                                                       at com.appdroid.develop.fantasyslide.UniversalActivity.onCreate(UniversalActivity.java:28) 
                                                                                       at android.app.Activity.performCreate(Activity.java:6303) 
                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402) 
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                                       at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5523) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                       at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768) 
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:496) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                       at me.imid.swipebacklayout.lib.app.SwipeBackActivityHelper.onActivityCreate(SwipeBackActivityHelper.java:28) 
                                                                                       at com.appdroid.develop.fantasyslide.UniversalActivity.onCreate(UniversalActivity.java:28) 
                                                                                       at android.app.Activity.performCreate(Activity.java:6303) 
                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402) 
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                                       at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5523) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                                                    Caused by: java.lang.NumberFormatException: Invalid int: "50.0dip"
                                                                                       at java.lang.Integer.invalidInt(Integer.java:138)
                                                                                       at java.lang.Integer.parse(Integer.java:410)
                                                                                       at java.lang.Integer.parseInt(Integer.java:367)
                                                                                       at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:133)
                                                                                       at android.content.res.TypedArray.getInt(TypedArray.java:357)
                                                                                       at me.imid.swipebacklayout.lib.SwipeBackLayout.<init>(SwipeBackLayout.java:142)
                                                                                       at me.imid.swipebacklayout.lib.SwipeBackLayout.<init>(SwipeBackLayout.java:129)
                                                                                       at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:623) 
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768) 
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:496) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                       at me.imid.swipebacklayout.lib.app.SwipeBackActivityHelper.onActivityCreate(SwipeBackActivityHelper.java:28) 
                                                                                       at com.appdroid.develop.fantasyslide.UniversalActivity.onCreate(UniversalActivity.java:28) 
                                                                                       at android.app.Activity.performCreate(Activity.java:6303) 
                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402) 
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                                       at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5523) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
01-27 15:29:27.983 10977-10977/? E/MQSEventManagerDelegate: failed to get MQSService.
`

**Comment by romtsn** [comment]
I have not seen any appearances of this library's package name in your stack trace. Are you sure that it's related to the library?

**Comment by sdroider** [comment]
"com.appdroid.develop" - its my prefix package name. Do you speak russian?

**Comment by romtsn** [comment]
Yes, I do speak russian. I mean the package name of my library `com.rom4ek.` is not presented in your crash stack trace.

**Comment by sdroider** [comment]
Блин, сорри мой косяк, так заработался что не в тот репозиторий скинул проблему) Тема закрыта)
