### ISSUE TITLE
App is crashing on API level 16, Android 4.1.1

### ISSUE THREAD

**Issue by mayurdg93** [rom4ek/ArcNavigationView#6]
I have added `compile 'com.rom4ek:arcnavigationview:1.0.3'` in the build.gradle. But, it is crashing on app start up. Below are the logs :

```
04-28 12:28:25.099 6184-6184/com.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.demo/com.demo.HomeActivity}: android.view.InflateException: Binary XML file line #12: Error inflating class com.rom4ek.arcnavigationview.ArcNavigationView
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2211)
                                                            at android.app.ActivityThread.access$600(ActivityThread.java:149)
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1300)
                                                            at android.os.Handler.dispatchMessage(Handler.java:99)
                                                            at android.os.Looper.loop(Looper.java:153)
                                                            at android.app.ActivityThread.main(ActivityThread.java:5086)
                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                            at java.lang.reflect.Method.invoke(Method.java:511)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
                                                            at dalvik.system.NativeStart.main(Native Method)
                                                         Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class com.rom4ek.arcnavigationview.ArcNavigationView
                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                            at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                            at com.demo.HomeActivity.onCreate(HomeActivity.java:54)
                                                            at android.app.Activity.performCreate(Activity.java:5020)
                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2211) 
                                                            at android.app.ActivityThread.access$600(ActivityThread.java:149) 
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1300) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                            at android.os.Looper.loop(Looper.java:153) 
                                                            at android.app.ActivityThread.main(ActivityThread.java:5086) 
                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                            at java.lang.reflect.Method.invoke(Method.java:511) 
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821) 
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584) 
                                                            at dalvik.system.NativeStart.main(Native Method) 
                                                         Caused by: java.lang.reflect.InvocationTargetException
                                                            at java.lang.reflect.Constructor.constructNative(Native Method)
                                                            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                            at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                            at com.demo.HomeActivity.onCreate(HomeActivity.java:54) 
                                                            at android.app.Activity.performCreate(Activity.java:5020) 
                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2211) 
                                                            at android.app.ActivityThread.access$600(ActivityThread.java:149) 
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1300) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                            at android.os.Looper.loop(Looper.java:153) 
                                                            at android.app.ActivityThread.main(ActivityThread.java:5086) 
                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                            at java.lang.reflect.Method.invoke(Method.java:511) 
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821) 
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584) 
                                                            at dalvik.system.NativeStart.main(Native Method) 
                                                         Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f020066
                                                            at android.content.res.Resources.getValue(Resources.java:1032)
                                                            at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:332)
                                                            at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
                                                            at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                                                            at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
                                                            at android.support.v7.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:425)
                                                            at android.support.design.internal.NavigationMenuPresenter$NavigationMenuAdapter.prepareMenuItems(NavigationMenuPresenter.java:519)
                                                            at android.support.design.internal.NavigationMenuPresenter$NavigationMenuAdapter.update(NavigationMenuPresenter.java:460)
                                                            at android.support.design.internal.NavigationMenuPresenter.updateMenuView(NavigationMenuPresenter.java:117)
                                                            at android.support.design.widget.NavigationView.inflateMenu(NavigationView.java:252)
                                                            at android.support.design.widget.NavigationView.<init>(NavigationView.java:174)
                                                            at android.support.design.widget.NavigationView.<init>(NavigationView.java:100)
                                                            at com.rom4ek.arcnavigationview.ArcNavigationView.<init>(ArcNavigationView.java:48)
                                                            at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                            at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                            at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                            at com.demo.HomeActivity.onCreate(HomeActivity.java:54) 
                                                            at android.app.Activity.performCreate(Activity.java:5020) 
                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2211) 
                                                            at android.app.ActivityThread.access$600(ActivityThread.java:149) 
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1300) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                            at android.os.Looper.loop(Looper.java:153) 
                                                            at android.app.ActivityThread.main(ActivityThread.java:5086) 
                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                            at java.lang.reflect.Method.invoke(Method.java:511) 
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821) 
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584) 
                                                            at dalvik.system.NativeStart.main(Native Method) 

```

**Comment by mayurdg93** [comment]
Solved.
